# 应用配置模板
# 复制此文件为 config.yaml 并根据实际环境修改配置

# 应用配置
app_name: "go-starter"
app_env: "dev"  # 可选值: dev, test, prod
app_port: "8000"
app_host: "0.0.0.0"

# MySQL 数据库配置
mysql:
  host: "localhost"
  port: 3306
  username: "root"
  password: "your_password"
  database: "go_starter"

# Redis 配置
redis:
  host: "localhost"
  port: 6379
  password: ""  # 如果Redis设置了密码，请填写
  database: 0 