# 应用配置
app_name: "go-starter"
app_env: "test"
app_port: "8000"
app_host: "0.0.0.0"

# MySQL 数据库配置
mysql:
  enable: true
  host: "localhost"
  port: 3306
  username: "root"
  password: "root"
  database: "test"
  pool_size: 10
  max_pool_size: 100

# Redis 配置
redis:
  enable: true
  host: "localhost"
  port: 6379
  password: ""
  database: 0
