# 应用配置
app_name: "go-starter"
app_env: "dev"  # 可选值: dev, test, prod
app_port: "8000"
app_host: "0.0.0.0"

# MySQL 数据库配置
mysql:
  enable: true
  host: "localhost"
  port: 3306
  username: "root"
  password: "your_password"
  database: "go_starter"
  pool_size: 10
  max_pool_size: 100

# Redis 配置
redis:
  enable: true
  host: "localhost"
  port: 6379
  password: ""
  database: 0 